### ISSUE TITLE
Await dont work

### ISSUE THREAD

**Issue by ghost** [arshadkazmi42/sqlite3-promisify#3]
IIf I try to use your example.
`const row = await Db.get(sql);
            ^^^^^

SyntaxError: await is only valid in async function
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)`

And without await it do not work

**Comment by arshadkazmi42** [comment]
> IIf I try to use your example.
> `const row = await Db.get(sql);
> ^^^^^
> 
> SyntaxError: await is only valid in async function
> at Module._compile (internal/modules/cjs/loader.js:723:23)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
> at Module.load (internal/modules/cjs/loader.js:653:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
> at Function.Module._load (internal/modules/cjs/loader.js:585:3)
> at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
> at startup (internal/bootstrap/node.js:283:19)
> at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)`
> 
> And without await it do not work

@AleksiGraba 

`await` calls should be wrapped inside an async function

to make it work you can define your function as async. Something like

```
const getFromDb = async () => {
    const row = await Db.get(sql);
}
```

if you do not want to use await, you can use it like a promise also

```
Db.get(sql).then(data => {
    // Do something with the result data
}).catch(err => {
   //  Do something on error
});
```

this does not needs your function to be async. Let me know if you need any other clarification with this

I  think readme is not properly demonstrating the exact way of using, sorry about that.
I will update the readme.

**Comment by ghost** [comment]
Okay, thanks it works if i replace the 'return' by 'console.log'
But still no result return, what do I wrong?

Code:

>
> module.exports = {
>   get_config : function(){
>    db.get(sql).then(data => {
>       return data
>     }).catch(err => {
>       console.log(err);
>       return err
>     })
>   }
> }
>

And if i try this, it returns:

> Promise { <pending> }
>


Code:

> module.exports = {
>   get_config : function(){
>    return db.get(sql).then(data => {
>       return data
>     }).catch(err => {
>       console.log(err);
>       return err
>     })
>   }
> }
>

But I want to use the result, not showing it only in the console.
Any Ideas?

Am Do., 28. Nov. 2019 um 05:57 Uhr schrieb Arshad Kazmi <
notifications@github.com>:

**Comment by arshadkazmi42** [comment]
> Okay, thanks it works if i replace the 'return' by 'console.log' But still no result return, what do I wrong? Code:
> module.exports = { get_config : function(){ db.get(sql).then(data => { return data }).catch(err => { console.log(err); return err }) } }
> And if i try this, it returns:
> Promise { <pending> }
> Code:
> module.exports = { get_config : function(){ return db.get(sql).then(data => { return data }).catch(err => { console.log(err); return err }) } }
> But I want to use the result, not showing it only in the console. Any Ideas? Am Do., 28. Nov. 2019 um 05:57 Uhr schrieb Arshad Kazmi < notifications@github.com>:
> […](#)

So,
this is returning a promise to get the value out of the promise either your calling function should do then or make your calling function async as shown in previous comment and add await on your get_config() 
call

if you have not worked with async await before i will suggest reading about it.
A simple explanation is available at this link https://javascript.info/async-await

**Comment by ghost** [comment]
I dont work, I just want a function what I can call to get my value.

like thit but with the Database, it canot be so complicated, I am lost:

console.log(test());


function test(){
return 'hi';
}


Am Do., 28. Nov. 2019 um 16:07 Uhr schrieb Arshad Kazmi <
notifications@github.com>:

**Comment by arshadkazmi42** [comment]
Complete implementation will be something like this
```js
// This is your calling function
const mainFunction = async () => {
   console.log(await getConfig());
   const results = await getConfig();
   console.log(results);
}

// This function will fetch data from db
// You will be calling this function  from mainFunction
const getConfig = async () => {
  const sql = 'SELECT * FROM configs';
  return await Db.get(sql);
}
```

**Comment by arshadkazmi42** [comment]
Closing this as no activity for two weeks. Feel free to re-open this, if you still have problems
